### PR TITLE
Add parse boolean from string

### PR DESCRIPTION
**Pull request by colderlord**
Parse boolean from string into bool.
Need tests....

### CODE REVIEW

**Comment by geoffreymcgill** [comment]
Hi. Thanks for the pull request. Can you create an [issue](https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/issues) detailing the defect that this pr will fix?

We will also require a [Deck](https://deck.net) demonstrating how to reproduce the error.

**Comment by colderlord** [comment]
Done!
[issue](https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/issues/79)

**Comment by geoffreymcgill** [comment]
Hi @colderlord – We cannot review the pr until the CLA has been signed. If you have any questions, please let me know.

**Comment by colderlord** [comment]
Hello @geoffreymcgill what should i do?)
i changed author in commit and authorize CLA.

**Comment by geoffreymcgill** [comment]
Hi @colderlord – All the checks have passed now, including the CLA. We'll begin our review of the pull request.

**Pull request merged**
