### PR TITLE
[52] DateTime fields aren't deserialised properly on [ObjectLiteral]

### LINKED ISSUE #52: DateTime fields aren't deserialised properly on [ObjectLiteral]
I was experimenting with `[ObjectLiteral]` for deserialisation performance and it makes things a lot faster, which is great. But it doesn't work on some properties, which is less great :(

#### Example

```csharp
public class Program
{
    public static void Main()
    {
        var settings = new JsonSerializerSettings 
        { 
            TypeNameHandling = Newtonsoft.Json.TypeNameHandling.Objects 
        };
        
        var x = new Person(DateTime.Now);
        var json = JsonConvert.SerializeObject(x, settings);
        var clone = JsonConvert.DeserializeObject<Person>(json, settings);

        Console.WriteLine(clone.Value.ToShortDateString());
    }
}

[ObjectLiteral(ObjectCreateMode.Constructor)]
public class Person
{
    public Person(DateTime value)
    {
        Value = value;
    }

    public DateTime Value { get; }
}
```

Available at https://deck.net/b683ffdeeed6ed939f88a5a0113f8118

The error is:

```
n.getFullYear is not a function
```

(because I think that it has put a string value in and claimed that it's a DateTime instance).

I think that more validation is required before taking the `[ObjectLiteral]` shortcut (which is definitely worthwhile considering how fast it is!). Maybe there needs to be a recursive check for incompatible properties? And I'm not sure if there could be edge cases relating to the fact that classes can be derived from `[ObjectLiteral]` classes without being `[ObjectLiteral]` themselves (though it's not allowed the other way around).

### PR DESCRIPTION
**Pull request by vladsch**
Fixes #52

### CODE REVIEW

**Comment by ProductiveRage** [comment]
Does this now work when [ObjectLiteral] is used instead of [ObjectLiteral(ObjectCreateMode.Constructor)]? I only found out this week that their behaviour seems to be different (the constructor version reports the correct type but the non-constructor version always reports "System.Object" and the meta data doesn't seem to be available).

**Comment by vladsch** [comment]
No, plain object literal has no type definition, therefore, no metadata for serialization.

**Comment by ProductiveRage** [comment]
Should that be a separate issue or is it insurmountable? If it's not possible then maybe there should be a deserialisation exception thrown - otherwise a runtime error is going to happen later on (when the DateTime property on the [ObjectLiteral] is accessed)?

**Comment by fabriciomurta** [comment]
Something went bad with the test case here once the changes to the other recent pull requests were merged. Reviewing will be required.

**Pull request merged**
