### PR TITLE
[106] Added ISerializationBinder

### PR DESCRIPTION
**Pull request by colderlord**
[131] Fix Error when deserialize object with `$type` but without `TypeNameHandling`

`.cs` files has been borrowed from original Newtonsoft.JSON
Need tests.

### CODE REVIEW

**Comment by fabriciomurta** [comment]
Hello, are you able to run the unit tests? We'd need them before we accept the pull request. You can base the unit test from an existing one, like this: [Case101.cs](https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/blob/v1.11.0-bridge17.4.0/Tests/Newtonsoft.Json.Tests/Issues/0100/Case101.cs).
One source file per issue.

It also looks like we didn't link the CLA restrictions here.

**Comment by fabriciomurta** [comment]
Just to add the references, this pull request is intended in addressing #131 and implementing #106.

**Comment by colderlord** [comment]
Ok. i'll do my best when i find some time...

**Comment by colderlord** [comment]
I was added tests. Look at them please.
2 tests fail due an error https://github.com/bridgedotnet/Bridge/issues/3746

**Comment by fabriciomurta** [comment]
Hello @colderlord! Sorry for the extended time in reviewing your pull request!

I was trying to merge this now in hopes we could include in the 1.14.0 version (tied to Bridge 17.7.0) but I got some compile errors, although no code file had conflicts with the current state of the repo. Unfortunately I won't have the opportunity now to give it a good review and still include in the release.

Let's try to tidy it up for the following release? If you have the chance to review it to the current state, drop a note here, and we'll merge it to `dev` at once, so it is guaranteed in the next version!

It is a pretty big change, but looks alright, except for a change in the unit test for issue 93. We shouldn't mix up unrelated changes in the same pull request, and the related issue (bridgedotnet/Bridge#3746 has been fixed for a while now (since 17.5.0).

I believe the compiler errors are but minor, it just complains about `error CS1574: XML comment has cref attribute 'Assembly' that could not be resolved`

**Comment by fabriciomurta** [comment]
```  Serialization\ISerializationBinder.cs(13,65): error CS1574: XML comment has cref attribute 'Assembly' that could not be resolved [A:\devel\Object.NET\Bridge.NET\git\Bridge.Newtonsoft.Json\Newtonsoft.Json\Newtonsoft.Json.csproj]
  Serialization\ISerializationBinder.cs(22,65): error CS1574: XML comment has cref attribute 'Assembly' that could not be resolved [A:\devel\Object.NET\Bridge.NET\git\Bridge.Newtonsoft.Json\Newtonsoft.Json\Newtonsoft.Json.csproj]
```
Just needs to remove the cref or change it to an appropriate name.

**Pull request closed without merging**
